name: redart
description: Reactive Programming for Dart
version: 0.0.1
repository: https://github.com/agent3bood/redart

environment:
  sdk: ^3.3.1

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
