name: redart
description: Reactive Programming for Dart
version: 0.0.1
repository: https://github.com/agent3bood/redart

environment:
  sdk: 3.6.0-149.3.beta
#  sdk: ">=3.6.0 <4.0.0"

dependencies:
  macros: ^0.1.0-main

dev_dependencies:
  _fe_analyzer_shared: any
  lints: ^3.0.0
  test: ^1.24.0

# https://github.com/dart-lang/language/blob/main/working/macros/example/pubspec.yaml
dependency_overrides:
  # Not yet published.
  _fe_analyzer_shared:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/_fe_analyzer_shared
      ref: main

analyzer:
  enable-experiment:
    - macros
